version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.0
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD= #Secreted
      - MYSQL_DATABASE=square_db
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    healthcheck:
      test: "mysql -uroot -p1234 square_db -e 'select 1'"
      interval: 5s
      timeout: 1s
      retries: 120

  dcs-api:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    image: delef/dcs-api
    build: .
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/square_db?useSSL=false
      SPRING_FLYWAY_URL: jdbc:mysql://mysqldb:3306/square_db?useSSL=false
